format = "$directory\n[>](bold purple)"
#(bg:#434C5E fg:#4C566A)

[directory]
format = "[$path]($style)"
style = "bold green"#"bg:#434C5E"
truncate_to_repo = false
truncation_length = 1
truncation_symbol = ""
